name: Python application

on:
  push:
    branches: [ 'playscribebot/*' ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DOCKER: ${{ secrets.DOCKER }}
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check environment variables
      run: |
        if [ -z $OPENAI_API_KEY ] || [ -z $DOCKER ] || [ -z $DOCKER_IMAGE ]; then
          echo [ERROR] Missing one of CI variables [OPENAI_API_KEY, DOCKER, DOCKER_IMAGE].
          exit 1
        fi
        $DOCKER run --rm --env OPENAI_API_KEY=$OPENAI_API_KEY -i $DOCKER_IMAGE --listmodels
    - name: Run application
      if: ${{ hashFiles('examples/input.txt') != '' }}
      run: |
        export URL=$( cat examples/input.txt ) && echo ${URL} && URL=${URL} make playscribebot || echo Could not extract wisdom > examples/result.txt
        cat examples/result.txt
        if [[ -f examples/result.txt ]] && [[ -n `git status --porcelain examples/result.txt` ]]; then
          git config --global user.email "playscribebot@telegram.org"
          git config --global user.name "Telegram Bot"
          git add examples/result.txt
          git commit -m "Update result.txt"
          git push
        fi